### ISSUE TITLE
Initial structures

### ISSUE THREAD

**Issue by ferroteam** [Tomoki-YAMASHITA/CrySPY#20]
Am I correct that I can supply initial structures to CrysPy to help to generate new structures based on them?

I tried to use CrysPy_utility to do so and supplied 1 experimental structure as initial guess. However, cryspy utility always stops with error message saying that total number of structures (20 in my case) is different than loaded number of structures from pkl file (1).

Is it an expected behavior?

**Comment by Tomoki-YAMASHITA** [comment]
================================
Please use the discussion page to ask questions.
https://github.com/Tomoki-YAMASHITA/CrySPY/discussions
=================================

Basically, no.
 However, if you use evolutionary algorithm (EA), CrySPY can generate new structures based on them.
It would require structure optimization (with VASP, QE, and so on), though. 

The error is an expected behavior.
If you want to load structures you have prepared, you must match the number of structures with the value of tot_struc in cryspy.in.
